create table if not exists usr_group
(
	id integer primary key,
	name varchar(20) not null,
	count integer default 0 not null
);

create table if not exists usr_user
(
	id integer generated by default as identity primary key,
	group_id integer,
	version integer default 0 not null,
	name varchar(20) not null,
	password varchar(50) not null,
	state varchar(20) not null
);