package test.jutil.jdo.it;

import io.jutil.jdo.core.engine.DataSourceOptions;
import io.jutil.jdo.core.engine.Jdo;
import io.jutil.jdo.core.engine.JdoBuilder;
import io.jutil.jdo.core.engine.JdoTemplate;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;

/**
 * @author Jin Zheng
 * @since 2022-03-02
 */
public class BaseTest {
	protected static Jdo jdo;
    protected static JdoTemplate jdoTemplate;

	public BaseTest() {
	}

	@BeforeAll
	public static void beforeAll() {
		DataSourceOptions dsOptions = new DataSourceOptions();
		dsOptions.setUrl("jdbc:hsqldb:mem:testDB");
		dsOptions.setTestWhileIdle(false);
		dsOptions.setValidationQuery(null);
		jdo = JdoBuilder.create()
				.setDataSourceOptions(dsOptions)
				.addScanPackages("test.jutil.jdo.model")
				.build();
		jdoTemplate = jdo.getJdoTemplate();
		createTable();
	}

	private static void createTable() {
		jdoTemplate.execute("""
				create table if not exists "group"
				(
					"id" integer primary key,
					"name" varchar(20) not null,
					"count" integer default 0 not null
				)""");
		jdoTemplate.execute("""
				create table if not exists "usr_user"
				(
					"id" integer generated by default as identity primary key,
					"group_id" integer,
					"version" integer default 0 not null,
					"name" varchar(20) not null,
					"password" varchar(50) not null,
					"state" varchar(20) default 'ACTIVE' not null
				)""");
	}

	protected void beforeEach() {
		jdoTemplate.execute("""
				insert into "group" ("id","name","count") values (1,'blue',1) """);
		jdoTemplate.execute("""
				insert into "group" ("id","name","count") values (2,'green',1) """);
	}

	protected void afterEach() {
		jdoTemplate.execute("""
				truncate table "group" """);
		jdoTemplate.execute("""
				truncate table "usr_user" """);
	}

	@AfterAll
	public static void afterAll() {
		if (jdo != null) {
			jdo.close();
		}
	}

}
